CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE public.meteor_recclass (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    CONSTRAINT "PK_meteor_recclass" PRIMARY KEY ("Id")
);

CREATE TABLE public.meteorites (
    "ExternalId" text NOT NULL,
    "Name" text NOT NULL,
    "Nametype" text,
    "RecclassId" integer,
    "Mass" double precision,
    "Fall" text,
    "Year" timestamp with time zone,
    "Reclat" double precision,
    "Reclong" double precision,
    "RawJson" jsonb NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_meteorites" PRIMARY KEY ("ExternalId"),
    CONSTRAINT "FK_meteorites_meteor_recclass_RecclassId" FOREIGN KEY ("RecclassId") REFERENCES public.meteor_recclass ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "IX_meteor_recclass_name" ON public.meteor_recclass (name);

CREATE INDEX "IX_meteorites_RecclassId" ON public.meteorites ("RecclassId");

CREATE INDEX "IX_meteorites_Year" ON public.meteorites ("Year");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251103203605_InitialCreate', '9.0.10');

COMMIT;

